name: weather_forecast
description: "A Flutter for an interview task for AppForge."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  curl_logger_dio_interceptor: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.0
  hydrated_bloc: ^9.1.5
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  build_runner: any
  bloc_test: any
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.1
  mockito: any
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
